### PR TITLE
Added IE11 Hash change Event

### PR DESCRIPTION
**Pull request by popara**

### CODE REVIEW

**Comment by edmellum** [comment]
Won't this disable popstate support on IE and only support hashchange?

**Comment by popara** [comment]
No, because handler `spawnPopState`   only works for changing the hash. And other E's don't complain.

Also I have used https://github.com/mjackson/history 's implementation as reference.

I have tested the solution and deployed it on production, and no complains so far :)

**Comment by edmellum** [comment]
You're saying `spawnPopState` **only** supports changing the hash? As far as I can see using `popstate` supports changing any part of the URL, not only the hash. The solution in https://github.com/mjackson/history supports both as it listens to **both** events, not just one or the other as it looks to me this PR does.

**Comment by popara** [comment]
Please, test it, and report the results.

You can pull my branch to try it out.

**Comment by edmellum** [comment]
I'm sorry, but I don't have the time to create a test case and test this. I can't see how it's supposed to work correctly. Do you have a minimal test case that shows it working with both hashchange and popstate in IE11 and Chrome?

**Comment by popara** [comment]
My friend,

Who here is bearing the burden of proof?

If you don't have time to test it, then obviously you don't need it, so why bother speculating about two line change?

You really expect that I will try convince that this is working?

**Comment by daymosik** [comment]
Your PR doesn't solve the issue, because You delete the whole popstate event from IE, and the issue is that IE doesn't trigger the popstate event only when the hash is changed in the url, but the rest of events are working fine in IE. With your "fix" the rest of navigation will not work in IE.

**Comment by evancz** [comment]
@popara, to the question:

> Who here is bearing the burden of proof?

It's on you. A high quality PR (1) has a description at all, (2) it outlines the key concerns and anticipates questions that may arise, and (3) provides as much evidence as possible to make the review an easy process.

Maintainers obviously can do all this stuff themselves, but at that point, what's the point of a PR? I can change code really easily. That's not the hard part.

This is what @process-bot tries says to everyone. https://github.com/elm-lang/navigation/pull/28#issuecomment-271002629

Anyway, hopefully that doesn't sound too harsh, and I will use this PR as a reference as I look into this.

**Comment by evancz** [comment]
I agree with @edmellum and @daymosik's analysis here. This will not listen to non-hash changes.

**Pull request closed without merging**
