### PR TITLE
Do not cache location

### PR DESCRIPTION
**Pull request by ghost**
For the use case where a user might enter a value manually into a url, fetch the location from the document again instead of using a cached location... I think this would fix an issue we are issue.

### CODE REVIEW

**Comment by OvermindDL1** [comment]
For note, I had to do the exact same change to fix what is likely a similar or same issue in my local version of Navigation and can confirm that this does fix that issue.

The issue being that when the elm app is pulled up 'later' than on page load, and the hash may change before then, then it does not get the correct and current value on init.

**Comment by ghost** [comment]
We have elm embedded inside angular.

After the angular app has been loaded, if a user modifies a url in the browser location bar directly by adding to the hash, I believe updateurl is fired. But update url fetches the url from the stale location value closed over when initwithflags is first invoked

**Comment by evancz** [comment]
Seems reasonable. Thanks!

**Comment by ghost** [comment]
I didn't check if it was cached anywhere else as well

**Comment by OvermindDL1** [comment]
> I didn't check if it was cached anywhere else as well

It does not seem to be from running my version of Navigation, it worked well then so this should be all for that issue.

**Pull request merged**
